trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  displayName: Nuget Restore
  inputs:
    command: 'restore'
    restoreSolution: '**/ImpostorHQ.Plugin.Fashionable.Designer.csproj'
    feedsToUse: 'select'
- task: MSBuild@1
  displayName: MS Build
  inputs:
    solution: '**/ImpostorHQ.Plugin.Fashionable.Designer.csproj'
    configuration: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: ".Net Restore"
  inputs:
    command: 'restore'
    projects: |
      **/*.csproj
      !**/ImpostorHQ.Plugin.Fashionable.Designer.csproj
    arguments: '--configuration $(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: ".Net Build"
  inputs:
    command: 'build'
    projects: |
      **/*.csproj
      !**/ImpostorHQ.Plugin.Fashionable.Designer.csproj
    arguments: '--configuration $(buildConfiguration) --no-restore'
- task: CopyFiles@2
  inputs:
    Contents: '**/Impostor.Commands.Core.dll'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ImpostorCommandsCore'
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    Contents: '**/ImpostorHQ.Plugin.Fashionable.dll'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ImpostorHQPlugin'
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    Contents: '**/ImpostorHQ.Plugin.HallOfShame.dll'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ImpostorHQPlugin'
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    Contents: '**/Plugin.Test.dll'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ImpostorHQPlugin'
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    Contents: '**/LogParser.exe'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/LogParser'
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    Contents: '**/ImpostorHQ.Plugin.Fashionable.Designer.exe'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/FashionableDesigner'
    flattenFolders: true

- publish: '$(Build.ArtifactStagingDirectory)/ImpostorCommandsCore'
  artifact: ImpostorCommandsCore
- publish: '$(Build.ArtifactStagingDirectory)/ImpostorHQPlugin'
  artifact: ImpostorHQPlugins
- publish: '$(Build.ArtifactStagingDirectory)/LogParser'
  artifact: LogParser
- publish: '$(Build.ArtifactStagingDirectory)/FashionableDesigner'
  artifact: FashionableDesigner

